/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.IntelliJTheme;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import model.Teachers;

/**
 *
 * @author 94762
 */
public class Class_registration extends javax.swing.JFrame {

    private static HashMap<String, Integer> subMap = new HashMap<>();
    private static HashMap<String, Teachers> teacherMap = new HashMap<>();
    private static HashMap<Integer, String> dayMap = new HashMap<>();
    private static HashMap<Integer, String> classMap = new HashMap<>();
    

    /**
     * Creates new form Class_registration
     */
    public Class_registration() {
        initComponents();
        loadSubjects();
        loadClassType();
        loadDays();
        loadClasses();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subjectCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        teacherCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dayCom = new javax.swing.JComboBox<>();
        timePicker1 = new com.raven.swing.TimePicker();
        class_time = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        alYear = new com.toedter.calendar.JYearChooser();
        class_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        intakeS = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        className = new javax.swing.JTextField();
        clsGenBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        feeTxt = new javax.swing.JTextField();
        rightPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        te_no_lbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        te_name_lbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        te_mob_lbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        te_sub_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        te_img = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class Registration");

        leftPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel1.setText("Subject");

        subjectCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subjectCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        subjectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel2.setText("Teacher");

        teacherCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Teacher" }));
        teacherCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherComboActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jLabel3.setText("Timelot");

        jLabel8.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel8.setText("Day");

        dayCom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dayCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timePicker1.setBackground(new java.awt.Color(33, 37, 43));
        timePicker1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        timePicker1.setForeground(new java.awt.Color(153, 153, 153));
        timePicker1.set24hourMode(true);
        timePicker1.setDisplayText(class_time);

        class_time.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel5.setText("AL Year");

        class_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        class_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel6.setText("Intake");

        intakeS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel7.setText("Class Name");

        className.setEditable(false);

        clsGenBtn.setText("Genarate");
        clsGenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsGenBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetBtn.setText("RESET");

        jLabel10.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel10.setText("class Type");

        jLabel11.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel11.setText("Class Fee");

        feeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(class_time, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(timePicker1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayCom, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alYear, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(class_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(feeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(subjectCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teacherCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(intakeS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(className)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clsGenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dayCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(class_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(feeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(className, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsGenBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel4.setText("Type anything related to classes");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel9.setText("Teacher No");

        te_no_lbl.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        te_no_lbl.setText("-----");

        jLabel13.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel13.setText("Teacher Name");

        te_name_lbl.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        te_name_lbl.setText("-----");

        jLabel15.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel15.setText("Mobile");

        te_mob_lbl.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        te_mob_lbl.setText("-----");

        jLabel17.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel17.setText("Subject");

        te_sub_lbl.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        te_sub_lbl.setText("-----");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Te_No", "Subject", "Class", "TimeLot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        te_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/nopreview.png"))); // NOI18N
        jPanel2.add(te_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/imagframe1.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(te_name_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(te_sub_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(te_no_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(te_mob_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(te_no_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(te_name_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(te_mob_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(te_sub_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Class Name", "Teacher", "TimeLot", "Subject", "Class Type", "Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("PRINT");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rightPanelLayout.createSequentialGroup()
                                .addComponent(jTextField2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subjectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboActionPerformed
        // TODO add your handling code here:

        int subId = subjectCombo.getSelectedIndex();
        loadTeachers(subId);
        System.out.println("Hii");

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `subjects` WHERE `Subno` = '" + subMap.get(subjectCombo.getSelectedItem()) + "'");
            if (rs.next()) {
                feeTxt.setText(String.valueOf(rs.getDouble("Price")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_subjectComboActionPerformed

    private void teacherComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherComboActionPerformed
        // TODO add your handling code here:

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `teachers` "
                    + "INNER JOIN `subjects` ON `teachers`.`subjects_Subno` = `subjects`.`Subno` WHERE `Tno` = '" + teacherCombo.getSelectedItem() + "'");

            if (rs.next()) {
                System.out.println(rs.getString("teFname"));

//                Teachers teacher = new Teachers();
//                teacher.setTeacherNo(rs.getString("Tno"));
//                teacher.setFirstName(rs.getString("teFname"));
//                teacher.setLastName(rs.getString("teLname"));
//                teacher.setMobile(rs.getString("teMobile"));
//                teacher.setSubid(rs.getInt("subjects_Subno"));
                te_no_lbl.setText(rs.getString("Tno"));
                te_name_lbl.setText(rs.getString("teFname") + " " + rs.getString("teLname"));
                te_mob_lbl.setText(rs.getString("teMobile"));
                te_sub_lbl.setText(rs.getString("subjects.name"));

//                teacherMap.put(rs.getString("Tno"), teacher);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_teacherComboActionPerformed

    private void clsGenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsGenBtnActionPerformed
        // TODO add your handling code here:

        String AlYear = String.valueOf(alYear.getYear());
        String SubjectCharacters = String.valueOf(subjectCombo.getSelectedItem()).toUpperCase();
        String TeacherNo = String.valueOf(teacherCombo.getSelectedItem());
        String ClassType = String.valueOf(class_type.getSelectedItem()).toUpperCase();
        String Intake = String.valueOf(intakeS.getValue());

        String Class_name = AlYear + "/" + "AL" + "/" + SubjectCharacters.substring(0, 2) + "/" + TeacherNo + "/" + ClassType.substring(0, 2) + "/" + "IN" + Intake;
        System.out.println(Class_name);
        className.setText(Class_name);

    }//GEN-LAST:event_clsGenBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        if (subjectCombo.getSelectedItem().equals("Select Subject")) {
            JOptionPane.showMessageDialog(this, "Invalid Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (teacherCombo.getSelectedItem().equals("Select Teacher")) {
            JOptionPane.showMessageDialog(this, "Inavlid First Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (dayCom.getSelectedItem().equals("Select Class Day")) {
            JOptionPane.showMessageDialog(this, "Invalid Day", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (class_time.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid Class Time", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (String.valueOf(alYear.getYear()).equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid Class Year", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (class_type.getSelectedItem().equals("Select Class Type")) {
            JOptionPane.showMessageDialog(this, "Invalid Class Type", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (feeTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid Class Fee", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (String.valueOf(intakeS.getValue()).equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid Intake", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (className.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid Class Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            String ClassName = className.getText();
            int SubjectId = subMap.get(String.valueOf(subjectCombo.getSelectedItem()));
            String TecherNo = String.valueOf(teacherCombo.getSelectedItem());
            String classTime = class_time.getText();
            int dayId = dayCom.getSelectedIndex();
            String AlYear = String.valueOf(alYear.getYear());
            String Intake = String.valueOf(intakeS.getValue());
            int classTypeId = class_type.getSelectedIndex();
            double class_fee = Double.parseDouble(feeTxt.getText());

            if (saveBtn.getText().equals("SAVE")) {

                try {

                    MySQL.execute("INSERT INTO `timelots` (`time`,`day_id`)"
                            + "VALUES ('" + classTime + "','" + dayId + "')");

                    ResultSet rs = MySQL.execute("SELECT * FROM `timelots` ORDER BY `id` DESC");

                    if (rs.next()) {

                        MySQL.execute("INSERT INTO `class` (`subjects_Subno`,`teachers_Tno`,`timeLots_id`,`class_name`,`al_year`,`intake`,`class_type_id`,`fee`)"
                                + "VALUES ('" + SubjectId + "','" + TecherNo + "','" + rs.getInt("id") + "','" + ClassName + "','" + AlYear + "','" + Intake + "','" + classTypeId + "','" + class_fee + "')");

                        JOptionPane.showMessageDialog(this, "Class Added Successfull", "System Message", JOptionPane.INFORMATION_MESSAGE);
                    }

                    loadClasses();
                    resetInfor();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            clsGenBtn.setEnabled(false);
            saveBtn.setText("UPDATE");
            resetBtn.setText("DELETE");

            int slectedRow = jTable2.getSelectedRow();
            String Selected_ClassName = String.valueOf(jTable2.getValueAt(slectedRow, 0));

            try {

                 ResultSet rs = MySQL.execute("SELECT * FROM `class` INNER JOIN `subjects` ON `class`.`subjects_Subno` = `subjects`.`Subno` "
                    + "INNER JOIN `timelots` ON `class`.`timeLots_id` = `timelots`.`id` INNER JOIN `class_type` ON `class`.`class_type_id` = `class_type`.`id` WHERE `class_name` = '"+Selected_ClassName+"'");
 
                 if(rs.next()){
                     
                     subjectCombo.setSelectedIndex(rs.getInt("subjects.Subno"));
                     teacherCombo.setSelectedItem(rs.getString("teachers_Tno"));
                     dayCom.setSelectedIndex(rs.getInt("timelots.day_id"));
                     class_time.setText(rs.getString("timelots.time"));
                     class_type.setSelectedIndex(rs.getInt("class_type_id"));
                     feeTxt.setText(String.valueOf(rs.getDouble("fee")));
                     intakeS.setValue(rs.getInt("intake"));
                     className.setText(rs.getString("class_name"));
                     
                 }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void resetInfor() {

        subjectCombo.setSelectedIndex(0);
        teacherCombo.setSelectedIndex(0);
        dayCom.setSelectedIndex(0);
        class_time.setText("");
        class_type.setSelectedIndex(0);
        feeTxt.setText("");
        intakeS.setValue(0);
        className.setText("");

    }

    /**
     * @param args the command line arguments
     */
    private void loadDays() {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `day`");

            Vector vec = new Vector();
            vec.add("Select Class Day");

            while (rs.next()) {
                vec.add(rs.getString("day_name"));
                dayMap.put(rs.getInt("id"), rs.getString("day_name"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vec);
            dayCom.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadClassType() {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `class_type`");

            Vector vec = new Vector();
            vec.add("Select Class Type");

            while (rs.next()) {
                vec.add(rs.getString("type"));
                classMap.put(rs.getInt("id"), rs.getString("type"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vec);
            class_type.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadSubjects() {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `subjects`");

            Vector subjectVector = new Vector();
            subjectVector.add("Select Subject");

            while (rs.next()) {
                subjectVector.add(rs.getString("name"));
                subMap.put(rs.getString("name"), rs.getInt("Subno"));

            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(subjectVector);
            subjectCombo.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTeachers(int subId) {

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `teachers` "
                    + "INNER JOIN `subjects` ON `teachers`.`subjects_Subno` = `subjects`.`Subno` WHERE `subjects_Subno` = '" + subId + "'");

            Vector<String> vec = new Vector<>();
            vec.add("Select Teacher");

            while (rs.next()) {
                vec.add(rs.getString("Tno"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vec);
            teacherCombo.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadClasses() {

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `class` INNER JOIN `subjects` ON `class`.`subjects_Subno` = `subjects`.`Subno` "
                    + "INNER JOIN `timelots` ON `class`.`timeLots_id` = `timelots`.`id` INNER JOIN `class_type` ON `class`.`class_type_id` = `class_type`.`id`");

            while (rs.next()) {

                Vector<String> vec = new Vector<>();
                vec.add(rs.getString("class_name"));
                vec.add(rs.getString("teachers_Tno"));
                vec.add(dayMap.get(rs.getInt("timelots.day_id")) + " " + rs.getTime("time"));
                vec.add(rs.getString("subjects.name"));
                vec.add(classMap.get(rs.getInt("class_type_id")));
                vec.add(rs.getString("fee"));

                model.addRow(vec);
                jTable2.setModel(model);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

//    public static void main(String args[]) {
//
//        /* Set the Theam look and feel */
//        IntelliJTheme.setup(Student_Registration.class.getResourceAsStream(
//                "/themes/one_dark.theme.json"));
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Class_registration().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser alYear;
    private javax.swing.JTextField className;
    private javax.swing.JTextField class_time;
    private javax.swing.JComboBox<String> class_type;
    private javax.swing.JButton clsGenBtn;
    private javax.swing.JComboBox<String> dayCom;
    private javax.swing.JTextField feeTxt;
    private javax.swing.JSpinner intakeS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> subjectCombo;
    private javax.swing.JLabel te_img;
    private javax.swing.JLabel te_mob_lbl;
    private javax.swing.JLabel te_name_lbl;
    private javax.swing.JLabel te_no_lbl;
    private javax.swing.JLabel te_sub_lbl;
    private javax.swing.JComboBox<String> teacherCombo;
    private com.raven.swing.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
