/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.IntelliJTheme;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import model.Students;

/**
 *
 * @author 94762
 */
public class Student_Teacher_Enrol extends javax.swing.JFrame {

    private static HashMap<Integer, String> subMap = new HashMap<>();
    private static HashMap<String, Students> studentsMap = new HashMap<>();
    private static HashMap<String, Integer> classMap = new HashMap<>();

    /**
     * Creates new form Student_Teacher_Enrol
     */
    public Student_Teacher_Enrol() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        loadSubjects();
        loadStudents();
        loadStudentEnrolClass("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        upPanel = new javax.swing.JPanel();
        typeAnyTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subCom1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tea_Com = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        class_com = new javax.swing.JComboBox<>();
        prntBtn = new javax.swing.JButton();
        undoBtn = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        infoPanel = new javax.swing.JPanel();
        imgPanel = new javax.swing.JPanel();
        teacherImg = new javax.swing.JLabel();
        imgFrame = new javax.swing.JLabel();
        basicInfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        teacher_mobLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        teacher_subjectLbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        teacher_nameLbl = new javax.swing.JLabel();
        BottomPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        stNo_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stName_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        findBtn = new javax.swing.JButton();
        st_sub_com = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        st_tea_COm = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        st_class_com = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        clrBtn = new javax.swing.JButton();
        st_addingBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        stu_nameLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stu_nicLbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        stu_numLbl = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        stu_mobLbl = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        crdPrintBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        stuInfo = new javax.swing.JPanel();
        stuImgPanel = new javax.swing.JPanel();
        stu_img = new javax.swing.JLabel();
        stuImgFrame = new javax.swing.JLabel();
        basicInfo2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        stu_mail_lbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        stu_name_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student And Teacher Enrolment For Class");

        TopPanel.setPreferredSize(new java.awt.Dimension(1370, 500));

        typeAnyTxt.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel1.setText("Type any things related to teachers");

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel3.setText("Subject");

        subCom1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        subCom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCom1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel4.setText("Class");

        tea_Com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Teacher" }));
        tea_Com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tea_ComActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel6.setText("Teacher");

        class_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class" }));
        class_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_comActionPerformed(evt);
            }
        });

        prntBtn.setText("PRINT");

        undoBtn.setText("UNDO");
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upPanelLayout = new javax.swing.GroupLayout(upPanel);
        upPanel.setLayout(upPanelLayout);
        upPanelLayout.setHorizontalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upPanelLayout.createSequentialGroup()
                        .addComponent(typeAnyTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subCom1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tea_Com, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(class_com, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prntBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        upPanelLayout.setVerticalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeAnyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(subCom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tea_Com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(class_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prntBtn)
                    .addComponent(undoBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        tablePanel.setLayout(new java.awt.GridLayout(1, 0));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Class Name", "Teacher", "ST_NO", "ST_Name", "REG_Date", "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tablePanel.add(jScrollPane1);

        infoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        imgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/nopreview.png"))); // NOI18N
        imgPanel.add(teacherImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 55, 250, 260));

        imgFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/imagframe1.png"))); // NOI18N
        imgPanel.add(imgFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        basicInfo.setPreferredSize(new java.awt.Dimension(325, 131));

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel5.setText("Mobile");

        teacher_mobLbl.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        teacher_mobLbl.setText("--");

        jLabel12.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel12.setText("Subject");

        teacher_subjectLbl.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        teacher_subjectLbl.setText("--");

        jLabel17.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel17.setText("Name");

        teacher_nameLbl.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        teacher_nameLbl.setText("--");

        javax.swing.GroupLayout basicInfoLayout = new javax.swing.GroupLayout(basicInfo);
        basicInfo.setLayout(basicInfoLayout);
        basicInfoLayout.setHorizontalGroup(
            basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(basicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGap(18, 18, 18)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoLayout.createSequentialGroup()
                        .addComponent(teacher_mobLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(teacher_nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(basicInfoLayout.createSequentialGroup()
                        .addComponent(teacher_subjectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        basicInfoLayout.setVerticalGroup(
            basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacher_nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacher_mobLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacher_subjectLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addComponent(basicInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "St_No", "Name", "Gender", "Mobile", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);

        jLabel9.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel9.setText("Students of the Institute");

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));

        jLabel13.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel13.setText("Student No");

        jLabel14.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel14.setText("Student Name");

        jLabel15.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel15.setText("Subject");

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        findBtn.setText("FIND");
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });

        st_sub_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        st_sub_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_sub_comActionPerformed(evt);
            }
        });

        jLabel11.setText("Teacher");

        st_tea_COm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Teacher" }));
        st_tea_COm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_tea_COmActionPerformed(evt);
            }
        });

        jLabel16.setText("Class Name");

        st_class_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class" }));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        clrBtn.setText("Clear");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });
        jPanel6.add(clrBtn);

        st_addingBtn.setText("Add To The Class");
        st_addingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_addingBtnActionPerformed(evt);
            }
        });
        jPanel6.add(st_addingBtn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stNo_txt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(findBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(st_tea_COm, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(st_sub_com, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(st_class_com, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(stName_txt))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(st_sub_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(st_tea_COm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(st_class_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Name");

        stu_nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        stu_nameLbl.setText("--");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("NIC No");

        stu_nicLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stu_nicLbl.setText("--");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Student No");

        stu_numLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stu_numLbl.setText("--");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Mobile");

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Class Name", "subject"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel8.add(jScrollPane3);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Other Classes");

        stu_mobLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stu_mobLbl.setText("--");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stu_numLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(stu_nicLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stu_mobLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)
                        .addComponent(stu_nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stu_nameLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(stu_numLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stu_nicLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(stu_mobLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        crdPrintBtn.setText("CARD PRINT");
        jPanel9.add(crdPrintBtn);

        jButton7.setText("CARD TO EMAIL");
        jPanel9.add(jButton7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel2.setText("Student Assign To The Class");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        stuInfo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        stuInfo.setPreferredSize(new java.awt.Dimension(333, 100));

        stu_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/nopreview.png"))); // NOI18N

        stuImgFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/imagframe1.png"))); // NOI18N

        javax.swing.GroupLayout stuImgPanelLayout = new javax.swing.GroupLayout(stuImgPanel);
        stuImgPanel.setLayout(stuImgPanelLayout);
        stuImgPanelLayout.setHorizontalGroup(
            stuImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuImgPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(stuImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stuImgFrame)
                    .addGroup(stuImgPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(stu_img))))
        );
        stuImgPanelLayout.setVerticalGroup(
            stuImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stuImgFrame)
            .addGroup(stuImgPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(stu_img))
        );

        basicInfo2.setPreferredSize(new java.awt.Dimension(325, 131));

        jLabel18.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel18.setText("Email");

        stu_mail_lbl.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        stu_mail_lbl.setText("--");

        jLabel20.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel20.setText("Name");

        stu_name_lbl.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        stu_name_lbl.setText("--");

        javax.swing.GroupLayout basicInfo2Layout = new javax.swing.GroupLayout(basicInfo2);
        basicInfo2.setLayout(basicInfo2Layout);
        basicInfo2Layout.setHorizontalGroup(
            basicInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfo2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(basicInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stu_name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_mail_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        basicInfo2Layout.setVerticalGroup(
            basicInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicInfo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stu_name_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basicInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stu_mail_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout stuInfoLayout = new javax.swing.GroupLayout(stuInfo);
        stuInfo.setLayout(stuInfoLayout);
        stuInfoLayout.setHorizontalGroup(
            stuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stuImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicInfo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addContainerGap())
        );
        stuInfoLayout.setVerticalGroup(
            stuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stuImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                        .addComponent(stuInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadSubjects() {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `subjects`");

            Vector subjectVector = new Vector();
            subjectVector.add("Select Subject");

            while (rs.next()) {
                subjectVector.add(rs.getString("name"));
                subMap.put(rs.getInt("Subno"), rs.getString("name"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(subjectVector);
            DefaultComboBoxModel model1 = new DefaultComboBoxModel(subjectVector);
            subCom1.setModel(model);
           
            st_sub_com.setModel(model1);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTeachers(int subId) {

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `teachers` "
                    + "WHERE `subjects_Subno` = '" + subId + "'");

            Vector<String> vec = new Vector<>();
            vec.add("Select Teacher");

            while (rs.next()) {
                vec.add(rs.getString("Tno"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vec);
            tea_Com.setModel(model);

            DefaultComboBoxModel modelSt = new DefaultComboBoxModel(vec);
            st_tea_COm.setModel(modelSt);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadClasses(String te_ID) {

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `class` "
                    + "WHERE `teachers_Tno` = '" + te_ID + "'");

            Vector<String> vec = new Vector<>();
            vec.add("Select Class");

            while (rs.next()) {
                vec.add(rs.getString("class_name"));
                classMap.put(rs.getString("class_name"), rs.getInt("classNo"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vec);
            class_com.setModel(model);

            DefaultComboBoxModel modelSt = new DefaultComboBoxModel(vec);
            st_class_com.setModel(modelSt);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadStudents() {

        DefaultTableModel model =   (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `students` INNER JOIN `gender` ON `students`.`gender_id` = `gender`.`id`");

            while (rs.next()) {

                Vector<String> vec = new Vector<>();
                vec.add(rs.getString("Sno"));
                vec.add(rs.getString("stFname") + " " + rs.getString("stLname"));
                vec.add(rs.getString("gender.gen"));
                vec.add(rs.getString("stMobile"));
                vec.add(rs.getString("stEmail"));

                model.addRow(vec);
                jTable2.setModel(model);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadStudentEnrolClass(String class_nam) {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
   
        String query;
        
        if(class_nam.equals("")){
             query = "SELECT * FROM `student_enrolment_class` INNER JOIN `class` ON `student_enrolment_class`.`class_classNo` = `class`.`classNo`"
                    + "INNER JOIN `students` ON `student_enrolment_class`.`students_Sno` = `students`.`Sno`";
        }else{
             query = "SELECT * FROM `student_enrolment_class` INNER JOIN `class` ON `student_enrolment_class`.`class_classNo` = `class`.`classNo`"
                    + "INNER JOIN `students` ON `student_enrolment_class`.`students_Sno` = `students`.`Sno` WHERE `classNo` = '"+classMap.get(class_nam)+"'";
        }
            
        try {

            ResultSet rs = MySQL.execute(query);

            while (rs.next()) {

                Vector<String> vec = new Vector<>();
                vec.add(rs.getString("class.class_name"));

                ResultSet te_rs = MySQL.execute("SELECT * FROM `teachers` WHERE `Tno` = '" + rs.getString("teachers_Tno") + "'");
                if (te_rs.next()) {
                    vec.add(te_rs.getString("teFname") + " " + te_rs.getString("teLname"));
                }

                vec.add(rs.getString("students.Sno"));
                vec.add(rs.getString("students.stFname") + " " + rs.getString("students.stLname"));
                vec.add(rs.getString("enrol_date"));

                ResultSet sub_rs = MySQL.execute("SELECT * FROM `subjects` WHERE `Subno` = '" + rs.getString("subjects_Subno") + "'");
                if (sub_rs.next()) {
                    vec.add(sub_rs.getString("name"));
                }

                model.addRow(vec);
                jTable1.setModel(model);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:

        String stu_no = stNo_txt.getText();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        if (stu_no.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter the student number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                ResultSet rs = MySQL.execute("SELECT * FROM `students` INNER JOIN `gender` ON `students`.`gender_id` = `gender`.`id` WHERE `Sno` = '" + stu_no + "'");

                if (rs.next()) {

                    Vector<String> vec = new Vector<>();
                    vec.add(rs.getString("Sno"));
                    vec.add(rs.getString("stFname") + " " + rs.getString("stLname"));
                    vec.add(rs.getString("gender.gen"));
                    vec.add(rs.getString("stMobile"));
                    vec.add(rs.getString("stEmail"));

                    model.addRow(vec);
                    jTable2.setModel(model);

                    Students student = new Students();
                    student.setStudentNumber(rs.getString("Sno"));
                    student.setFirstName(rs.getString("stFname"));
                    student.setLastName(rs.getString("stLname"));
                    student.setNic(rs.getString("stNic"));
                    student.setDob(rs.getString("dob"));
                    student.setGender(rs.getString("gender.gen"));
                    student.setMobile(rs.getString("stMobile"));
                    student.setEmail(rs.getString("stEmail"));

                    studentsMap.put(rs.getString("Sno"), student);

                    stName_txt.setText(rs.getString("stFname") + " " + rs.getString("stLname"));
                    stu_name_lbl.setText(rs.getString("stFname") + " " + rs.getString("stLname"));
                    stu_mail_lbl.setText(rs.getString("stEmail"));
                    stu_mail_lbl.setText(rs.getString("stEmail"));
                }

                loadCurrentClass(stu_no);

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_findBtnActionPerformed

    private void loadCurrentClass(String stu_no) {

        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `student_enrolment_class` INNER JOIN `class` ON `student_enrolment_class`.`class_classNo` = `class`.`classNo`"
                    + "WHERE `students_Sno` = '" + stu_no + "'");

            while (rs.next()) {

                Vector<String> vec = new Vector<>();
                vec.add(rs.getString("class.class_name"));
                vec.add(subMap.get(rs.getInt("class.subjects_Subno")));

                model.addRow(vec);
                jTable3.setModel(model);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void subCom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCom1ActionPerformed
        // TODO add your handling code here:

        int subId = subCom1.getSelectedIndex();
        loadTeachers(subId);

    }//GEN-LAST:event_subCom1ActionPerformed

    private void tea_ComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tea_ComActionPerformed
        // TODO add your handling code here:

        String te_ID = String.valueOf(tea_Com.getSelectedItem());
        loadClasses(te_ID);
        loadTeacherInfor(te_ID);
       
    }//GEN-LAST:event_tea_ComActionPerformed

    private void st_sub_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_sub_comActionPerformed
        // TODO add your handling code here:
        int subId = st_sub_com.getSelectedIndex();
        loadTeachers(subId);
    }//GEN-LAST:event_st_sub_comActionPerformed

    private void st_tea_COmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_tea_COmActionPerformed
        // TODO add your handling code here:
        String te_ID = String.valueOf(st_tea_COm.getSelectedItem());
        loadClasses(te_ID);
        loadTeacherInfor(te_ID);
    }//GEN-LAST:event_st_tea_COmActionPerformed

    private void st_addingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_addingBtnActionPerformed
        // TODO add your handling code here:

        if (stNo_txt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter the student number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (st_sub_com.getSelectedItem().equals("Select Subject")) {
            JOptionPane.showMessageDialog(this, "Please select a subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (st_tea_COm.getSelectedItem().equals("Select Teacher")) {
            JOptionPane.showMessageDialog(this, "Please select a teacher", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (st_class_com.getSelectedItem().equals("Select Class")) {
            JOptionPane.showMessageDialog(this, "Please select a class", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            String Stu_No = stNo_txt.getText();
            int Class_no = classMap.get(st_class_com.getSelectedItem());

            // System.out.println(Class_no);
            Date date = new Date();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String currentDT = format.format(date);

            try {

                MySQL.execute("INSERT INTO `student_enrolment_class` (`enrol_date`,`students_Sno`,`class_classNo`)"
                        + "VALUES ('" + currentDT + "','" + Stu_No + "','" + Class_no + "')");

                JOptionPane.showMessageDialog(this, "Student Assign Successfull", "System Message", JOptionPane.INFORMATION_MESSAGE);

                stu_nameLbl.setText(studentsMap.get(Stu_No).getFirstName() + " " + studentsMap.get(Stu_No).getLastName());
                stu_numLbl.setText(studentsMap.get(Stu_No).getStudentNumber());
                stu_nicLbl.setText(studentsMap.get(Stu_No).getNic());
                stu_mobLbl.setText(studentsMap.get(Stu_No).getMobile());

                clearAsign();
                loadStudentEnrolClass("");

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_st_addingBtnActionPerformed


    private void loadTeacherInfor(String Te_no) {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `teachers` INNER JOIN `subjects` ON `teachers`.`subjects_Subno` = `subjects`.`Subno` WHERE `Tno` = '" + Te_no + "'");

            if (rs.next()) {
                teacher_nameLbl.setText(rs.getString("teFname") + " " + rs.getString("teLname"));
                teacher_mobLbl.setText(rs.getString("teMobile"));
                teacher_subjectLbl.setText(rs.getString("subjects.name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void clearAsign() {

        stu_nameLbl.setText("--");
        stu_numLbl.setText("--");
        stu_nicLbl.setText("--");
        stu_mobLbl.setText("--");
        stNo_txt.setText("");
        stName_txt.setText("");
        stu_name_lbl.setText("--");
        stu_mail_lbl.setText("--");
        teacher_nameLbl.setText("--");
        teacher_mobLbl.setText("--");
        teacher_subjectLbl.setText("--");

        st_sub_com.setSelectedIndex(0);
        st_tea_COm.setSelectedIndex(0);
        st_class_com.setSelectedIndex(0);
        loadCurrentClass("");

    }

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        // TODO add your handling code here:

        clearAsign();
        loadStudents();
    }//GEN-LAST:event_clrBtnActionPerformed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
        // TODO add your handling code here:
        loadStudentEnrolClass("");
    }//GEN-LAST:event_undoBtnActionPerformed

    private void class_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_comActionPerformed
        // TODO add your handling code here:
         loadStudentEnrolClass(String.valueOf(class_com.getSelectedItem()));
         System.out.println(String.valueOf(class_com.getSelectedItem()));
    }//GEN-LAST:event_class_comActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//        /* Set the Theam look and feel */
//        IntelliJTheme.setup(Student_Teacher_Enrol.class.getResourceAsStream(
//                "/themes/one_dark.theme.json"));
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Student_Teacher_Enrol().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel basicInfo;
    private javax.swing.JPanel basicInfo2;
    private javax.swing.JComboBox<String> class_com;
    private javax.swing.JButton clrBtn;
    private javax.swing.JButton crdPrintBtn;
    private javax.swing.JButton findBtn;
    private javax.swing.JLabel imgFrame;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton prntBtn;
    private javax.swing.JTextField stName_txt;
    private javax.swing.JTextField stNo_txt;
    private javax.swing.JButton st_addingBtn;
    private javax.swing.JComboBox<String> st_class_com;
    private javax.swing.JComboBox<String> st_sub_com;
    private javax.swing.JComboBox<String> st_tea_COm;
    private javax.swing.JLabel stuImgFrame;
    private javax.swing.JPanel stuImgPanel;
    private javax.swing.JPanel stuInfo;
    private javax.swing.JLabel stu_img;
    private javax.swing.JLabel stu_mail_lbl;
    private javax.swing.JLabel stu_mobLbl;
    private javax.swing.JLabel stu_nameLbl;
    private javax.swing.JLabel stu_name_lbl;
    private javax.swing.JLabel stu_nicLbl;
    private javax.swing.JLabel stu_numLbl;
    private javax.swing.JComboBox<String> subCom1;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JComboBox<String> tea_Com;
    private javax.swing.JLabel teacherImg;
    private javax.swing.JLabel teacher_mobLbl;
    private javax.swing.JLabel teacher_nameLbl;
    private javax.swing.JLabel teacher_subjectLbl;
    private javax.swing.JTextField typeAnyTxt;
    private javax.swing.JButton undoBtn;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
