/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Image;
import java.io.File;
import model.MySQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Students;

/**
 *
 * @author 94762
 */
public class Student_Registration extends javax.swing.JFrame {

    
    public static HashMap<String, Integer> cityMap = new HashMap<>();
    public static Vector<Students> studentVector = new Vector<>();
    public static HashMap<String, Students> studentsMap = new HashMap<>();
    
    
    
    /**
     * Creates new form Student_Registration_1
     */
    public Student_Registration() {
        
        initComponents();
        loadCity();
        loadStudents();
//         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        leftPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imgPanel = new javax.swing.JPanel();
        stuImg = new javax.swing.JLabel();
        imgFrame = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        clr_img_btn = new javax.swing.JButton();
        add_img_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        mainPanel = new javax.swing.JPanel();
        userInfoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        address2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        g_occu = new javax.swing.JTextField();
        st_no = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        g_mobile = new javax.swing.JTextField();
        st_fname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        g_email = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        action_btn_panel = new javax.swing.JPanel();
        clr_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        st_nic = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        g_name = new javax.swing.JTextField();
        city_Combo = new javax.swing.JComboBox<>();
        st_no_genarate = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        st_lname = new javax.swing.JTextField();
        stuTablePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        anything_text = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Registration");

        leftPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        leftPanel.setPreferredSize(new java.awt.Dimension(330, 650));

        imgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stuImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/nopreview.png"))); // NOI18N
        imgPanel.add(stuImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        imgFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/imagframe1.png"))); // NOI18N
        imgFrame.setText("jLabel14");
        imgPanel.add(imgFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 310, 340));

        btnPanel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        clr_img_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clr_img_btn.setText("CLEAR");
        btnPanel.add(clr_img_btn);

        add_img_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_img_btn.setText("ADD IMAGE");
        add_img_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_img_btnActionPerformed(evt);
            }
        });
        btnPanel.add(add_img_btn);

        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_START);

        userInfoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        address1.setColumns(20);
        address1.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N
        address1.setRows(5);
        jScrollPane2.setViewportView(address1);

        address2.setColumns(20);
        address2.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N
        address2.setRows(5);
        jScrollPane3.setViewportView(address2);

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel2.setText("Student No");

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel4.setText("Date Of Birth");

        jDateChooser1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel5.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel10.setText("Guardian Name");

        jLabel6.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel6.setText("Mobile");

        jLabel7.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel8.setText("Address Line 1");

        jLabel11.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel11.setText("Occupation");

        jLabel9.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel9.setText("Address Line 2");

        g_occu.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        st_no.setEditable(false);
        st_no.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel12.setText("Mobile");

        g_mobile.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        st_fname.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel13.setText("Email");

        g_email.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.setActionCommand("1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.setActionCommand("2");

        mobile.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        email.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        action_btn_panel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        clr_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clr_btn.setText("CLEAR");
        clr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_btnActionPerformed(evt);
            }
        });
        action_btn_panel.add(clr_btn);

        save_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        save_btn.setText("SAVE");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        action_btn_panel.add(save_btn);

        jLabel15.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel15.setText("NIC No");

        st_nic.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel16.setText(" City");

        g_name.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        city_Combo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        city_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        st_no_genarate.setText("Genarate");
        st_no_genarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_no_genarateActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel17.setText("Last Name");

        st_lname.setFont(new java.awt.Font("Segoe UI Variable", 0, 15)); // NOI18N

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(st_no, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(st_no_genarate))
                            .addComponent(jLabel16)
                            .addGroup(userInfoPanelLayout.createSequentialGroup()
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel15))
                                .addGap(46, 46, 46)
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mobile, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userInfoPanelLayout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton2)))
                                    .addComponent(st_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(137, 137, 137))
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userInfoPanelLayout.createSequentialGroup()
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(83, 83, 83)
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g_email)
                                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                                        .addComponent(g_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(action_btn_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(userInfoPanelLayout.createSequentialGroup()
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(34, 34, 34)
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email)
                                    .addComponent(jScrollPane3)))
                            .addGroup(userInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(58, 58, 58)
                                .addComponent(st_fname))
                            .addGroup(userInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(st_lname))
                            .addGroup(userInfoPanelLayout.createSequentialGroup()
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g_occu)
                                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                                        .addComponent(city_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(g_name))))
                        .addContainerGap())))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(st_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(st_no_genarate)))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(st_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(st_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(st_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(city_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(g_occu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(g_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(g_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(action_btn_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        stuTablePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel14.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel14.setText("Type any things related to students");

        anything_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anything_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anything_textKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(240, 240, 240))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(anything_text, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anything_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "St_No", "Name", "Gender", "DOB", "Mobile", "Gu/Mobile"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout stuTablePanelLayout = new javax.swing.GroupLayout(stuTablePanel);
        stuTablePanel.setLayout(stuTablePanelLayout);
        stuTablePanelLayout.setHorizontalGroup(
            stuTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stuTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stuTablePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        stuTablePanelLayout.setVerticalGroup(
            stuTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stuTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stuTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadCity() {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `city`");

            Vector cityVector = new Vector();
            cityVector.add("Select City");

            while (rs.next()) {
                cityVector.add(rs.getString("name"));
                cityMap.put(rs.getString("name"), rs.getInt("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(cityVector);
            city_Combo.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadStudents() {

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `students` INNER JOIN `gender` ON `students`.`gender_id` = `gender`.`id` "
                    + "INNER JOIN `student_address` ON `students`.`Sno` = `student_address`.`students_Sno` ORDER BY `reg_datetime` ASC");

            while (rs.next()) {

                Vector<String> vec = new Vector<>();
                vec.add(rs.getString("Sno"));
                vec.add(rs.getString("stFname") + " " + rs.getString("stLname"));
                vec.add(rs.getString("gender.gen"));
                vec.add(rs.getString("dob"));
                vec.add(rs.getString("stMobile"));
                vec.add(rs.getString("stGuardMobile"));

                model.addRow(vec);
                jTable2.setModel(model);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    private void clearinfor() {

        st_no.setText("");
        st_nic.setText("");
        st_fname.setText("");
        st_lname.setText("");
        mobile.setText("");
        email.setText("");
        address1.setText("");
        address2.setText("");
        city_Combo.setSelectedIndex(0);
        g_name.setText("");
        g_occu.setText("");
        g_mobile.setText("");
        g_email.setText("");
        jRadioButton1.setSelected(true);

    }

    
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed

        int cityId;

        String stNumber = st_no.getText();
        String stNIC = st_nic.getText();
        String stFName = st_fname.getText();
        String stLanem = st_lname.getText();
        String stmobile = mobile.getText();
        String stEmail = email.getText();
        String stAdress1 = address1.getText();
        String stAdress2 = address2.getText();
        String city = String.valueOf(city_Combo.getSelectedItem());
        String Gurad_name = g_name.getText();
        String Gurad_Occu = g_occu.getText();
        String Gurad_mobile = g_mobile.getText();
        String Gurad_email = g_email.getText();
        ButtonModel genderSelection = buttonGroup1.getSelection();

        Date date = jDateChooser1.getDate();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        if (stNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Student Number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (stFName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid First Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (stLanem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (stNIC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid NIC", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (date == null) {
            JOptionPane.showMessageDialog(this, "Inavlid DOB", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (genderSelection == null) {
            JOptionPane.showMessageDialog(this, "Inavlid gender", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (stmobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Mobile", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (stEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Email", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (stAdress1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Address", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (city.equals("Select City")) {
            JOptionPane.showMessageDialog(this, "Inavlid City", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Gurad_name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Guradian Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Gurad_mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Guradian Mobile", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            String gender = buttonGroup1.getSelection().getActionCommand();
            cityId = cityMap.get(city);
            String stDOB = format.format(date);
            System.out.println(stDOB);

            if (save_btn.getText().equals("SAVE")) {
                //Get Currrent date and time------------------------------------------
                Date currentDate = new Date();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String curentDate = format1.format(currentDate);

                try {

                    MySQL.execute("INSERT INTO `students` (`Sno`,`stNic`,`stFname`,`stLname`,`dob`,`stMobile`,`stEmail`,`stGuardName`,`stGuardOccu`,`stGuardMobile`,`stGuradEmail`,`gender_id`,`reg_datetime`)"
                            + "VALUES ('" + stNumber + "','" + stNIC + "','" + stFName + "','" + stLanem + "','" + stDOB + "','" + stmobile + "','" + stEmail + "','" + Gurad_name + "','" + Gurad_Occu + "',"
                                    + "'" + Gurad_mobile + "','" + Gurad_email + "','" + gender + "','" + curentDate + "')");

                    MySQL.execute("INSERT INTO `student_address` (`line1`,`line2`,`city_id`,`students_Sno`)"
                            + "VALUES ('" + stAdress1 + "','" + stAdress2 + "','" + cityId + "','" + stNumber + "')");

                    JOptionPane.showMessageDialog(this, "Student Added Success", "System Message", JOptionPane.INFORMATION_MESSAGE);

                    loadStudents();
                    clearinfor();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {

                try {

                    int selectedRow = jTable2.getSelectedRow();

                    String stu_no = String.valueOf(jTable2.getValueAt(selectedRow, 0));

                    MySQL.execute("UPDATE `students` SET `stFname` = '" + stFName + "',`stLname` = '" + stLanem + "',`stNic` = '" + stNIC + "',`dob` = '" + stDOB + "', `stMobile` = '" + stmobile + "',"
                            + "`stEmail` = '" + stEmail + "',`stGuardName` = '" + Gurad_name + "',`stGuardOccu` = '" + Gurad_Occu + "',`stGuardMobile` = '" + Gurad_mobile + "',`stGuradEmail` = '" + Gurad_email + "',`gender_id` = '" + gender + "'"
                            + "WHERE `Sno` = '" + stu_no + "'");

                    MySQL.execute("UPDATE `student_address` SET `line1` = '" + stAdress1 + "', `line2` = '" + stAdress2 + "', `city_id` = '" + cityId + "' WHERE `students_Sno` = '" + stu_no + "'");

                    loadStudents();
                    clearinfor();
                    save_btn.setText("SAVE");
                    clr_btn.setText("CLEAR");
                    st_no_genarate.setEnabled(true);

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }


    }//GEN-LAST:event_save_btnActionPerformed

    
    private void st_no_genarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_no_genarateActionPerformed
        // TODO add your handling code here:

        Random random = new Random();
        int code = random.nextInt(9000) + 1000;
        int rowCount;
        try {
            ResultSet rs = MySQL.execute("SELECT COUNT(*) AS row_count FROM `students`");

            if (rs.next()) {

                rowCount = rs.getInt("row_count");
                int whichStudent = rowCount + 1;
                String newStuNumber = "ST_" + whichStudent + "_" + code;
                System.out.println(newStuNumber);

                st_no.setText(newStuNumber);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_st_no_genarateActionPerformed

    private void clr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_btnActionPerformed
        // TODO add your handling code here:
        if (clr_btn.getText().equals("CLEAR")) {
            clearinfor();
        } else {

            int selectedRow = jTable2.getSelectedRow();
            String stu_no = String.valueOf(jTable2.getValueAt(selectedRow, 0));

            try {

                MySQL.execute("DELETE FROM `student_address` WHERE `students_Sno` = '" + stu_no + "'");
                MySQL.execute("DELETE FROM `students` WHERE `Sno` = '"+stu_no+"'");
                JOptionPane.showMessageDialog(this, "Student Delete Successfull");
                loadStudents();
                clearinfor();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_clr_btnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            st_no_genarate.setEnabled(false);;
            save_btn.setText("UPDATE");
            clr_btn.setText("DELETE");

            int slectedRow = jTable2.getSelectedRow();
            String Selected_StuNo = String.valueOf(jTable2.getValueAt(slectedRow, 0));

            try {
                ResultSet rs = MySQL.execute("SELECT * FROM `students` INNER JOIN `gender` ON `students`.`gender_id` = `gender`.`id` "
                        + "INNER JOIN `student_address` ON `students`.`Sno` = `student_address`.`students_Sno` WHERE `Sno` = '" + Selected_StuNo + "'");

                if (rs.next()) {

                    st_no.setText(rs.getString("Sno"));
                    st_fname.setText(rs.getString("stFname"));
                    st_lname.setText(rs.getString("stLname"));
                    st_nic.setText(rs.getString("stNic"));

                    Date dobDate = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    dobDate = dateFormat.parse(rs.getString("dob"));
                    jDateChooser1.setDate(dobDate);

                    if ("Male".equals(rs.getString("gender.gen"))) {
                        jRadioButton1.setSelected(true);
                    } else {
                        jRadioButton2.setSelected(true);
                    }

                    mobile.setText(rs.getString("stMobile"));
                    email.setText(rs.getString("stEmail"));
                    address1.setText(rs.getString("student_address.line1"));
                    address2.setText(rs.getString("student_address.line2"));
                    city_Combo.setSelectedIndex(rs.getInt("student_address.city_id"));
                    g_name.setText(rs.getString("stGuardName"));
                    g_occu.setText(rs.getString("stGuardOccu"));
                    g_mobile.setText(rs.getString("stGuardMobile"));
                    g_email.setText(rs.getString("stGuradEmail"));

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void anything_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anything_textKeyReleased
        // TODO add your handling code here:

        System.out.println(anything_text.getText());

        if (anything_text.getText().equals("")) {
            loadStudents();
        } else {
            

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);

            try {
                ResultSet rs = MySQL.execute("SELECT * FROM `students` INNER JOIN `gender` ON `students`.`gender_id` = `gender`.`id` "
                        + " WHERE `stFname` LIKE '" + anything_text.getText() + "%' OR `stLname` LIKE '" + anything_text.getText() + "%' OR"
                        + "`stNic` LIKE '" + anything_text.getText() + "%' OR `gen` LIKE '" + anything_text.getText() + "%'"
                        + "OR `dob` LIKE '" + anything_text.getText() + "%' OR `stMobile` LIKE '" + anything_text.getText() + "%'");

                while (rs.next()) {

                    Vector<String> vec = new Vector<>();
                    vec.add(rs.getString("Sno"));
                    vec.add(rs.getString("stFname") + " " + rs.getString("stLname"));
                    vec.add(rs.getString("gender.gen"));
                    vec.add(rs.getString("dob"));
                    vec.add(rs.getString("stMobile"));
                    vec.add(rs.getString("stGuardMobile"));

                    model.addRow(vec);
                    jTable2.setModel(model);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_anything_textKeyReleased

    private void add_img_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_img_btnActionPerformed
      
        
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","jpeg","png");
        file.addChoosableFileFilter(filter);
        
        int result = file.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION){
            
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            
           ImageIcon SelectedImg = new ImageIcon(path);
           Image img = SelectedImg.getImage();
           Image newImg = img.getScaledInstance(stuImg.getWidth(), stuImg.getHeight(), Image.SCALE_SMOOTH);
           stuImg.setIcon(new ImageIcon(newImg));
        }
        
    }//GEN-LAST:event_add_img_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    
//        public static void main(String args[]) {
//
//        /* Set the Theam look and feel */
//        IntelliJTheme.setup(Student_Registration.class.getResourceAsStream(
//                "/themes/one_dark.theme.json"));
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Student_Registration().setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action_btn_panel;
    private javax.swing.JButton add_img_btn;
    private javax.swing.JTextArea address1;
    private javax.swing.JTextArea address2;
    private javax.swing.JTextField anything_text;
    private javax.swing.JPanel btnPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> city_Combo;
    private javax.swing.JButton clr_btn;
    private javax.swing.JButton clr_img_btn;
    private javax.swing.JTextField email;
    private javax.swing.JTextField g_email;
    private javax.swing.JTextField g_mobile;
    private javax.swing.JTextField g_name;
    private javax.swing.JTextField g_occu;
    private javax.swing.JLabel imgFrame;
    private javax.swing.JPanel imgPanel;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField mobile;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField st_fname;
    private javax.swing.JTextField st_lname;
    private javax.swing.JTextField st_nic;
    private javax.swing.JTextField st_no;
    private javax.swing.JButton st_no_genarate;
    private javax.swing.JLabel stuImg;
    private javax.swing.JPanel stuTablePanel;
    private javax.swing.JPanel userInfoPanel;
    // End of variables declaration//GEN-END:variables
}
