/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.IntelliJTheme;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author 94762
 */
public class Teacher_Enrolment extends javax.swing.JFrame {

    private static HashMap<String, Integer> cityMap = new HashMap<>();
    private static HashMap<String, Integer> subMap = new HashMap<>();

    /**
     * Creates new form Teacher_Enrolment
     */
    public Teacher_Enrolment() {
        initComponents();
        loadCountry();
        loadSubjects();
        loadTeachers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        leftPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imgFramePanel = new javax.swing.JPanel();
        userImg = new javax.swing.JLabel();
        imgFrame = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        clearBtn = new javax.swing.JButton();
        addImgBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        mainPanel = new javax.swing.JPanel();
        mainLeft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        te_no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        te_fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        te_lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        te_nic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        te_mobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        te_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        te_line1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        te_line2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edu_quali = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        prof_quali = new javax.swing.JTextArea();
        genarate_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        clr_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cityCom = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        subCom = new javax.swing.JComboBox<>();
        mainRight = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        anything_txt = new javax.swing.JTextField();
        print_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teacher Enrolment");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        imgFramePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/nopreview.png"))); // NOI18N
        imgFramePanel.add(userImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 250));

        imgFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetes/img/imagframe1.png"))); // NOI18N
        imgFramePanel.add(imgFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 8, 310, 340));

        btnPanel.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn.setText("CLEAR");
        btnPanel.add(clearBtn);

        addImgBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addImgBtn.setText("ADD IMAGE");
        btnPanel.add(addImgBtn);

        jCalendar2.setForeground(new java.awt.Color(204, 204, 204));
        jCalendar2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jCalendar2.setDecorationBackgroundColor(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgFramePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_START);

        mainLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel1.setText("Teacher No");

        te_no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel2.setText("First Name");

        te_fname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel3.setText("Last Name");

        te_lname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel4.setText("Date Of Birth");

        jDateChooser1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel5.setText("Gender");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setActionCommand("1");
        jRadioButton1.setText("Male");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setActionCommand("2");
        jRadioButton2.setText("Female");

        jLabel13.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel13.setText("NIC No");

        te_nic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel6.setText(" Mobile");

        te_mobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel7.setText("Email");

        te_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel8.setText("Address Line 1");

        te_line1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel9.setText("Address Line 2");

        te_line2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel10.setText("Edu. Qualification");

        edu_quali.setColumns(20);
        edu_quali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edu_quali.setRows(5);
        jScrollPane2.setViewportView(edu_quali);

        jLabel11.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel11.setText("Prof. Qualification");

        prof_quali.setColumns(20);
        prof_quali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prof_quali.setRows(5);
        jScrollPane3.setViewportView(prof_quali);

        genarate_btn.setText("Genarate");
        genarate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarate_btnActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        clr_btn.setText("CLEAR");
        clr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_btnActionPerformed(evt);
            }
        });
        jPanel3.add(clr_btn);

        save_btn.setText("SAVE");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel3.add(save_btn);

        jLabel12.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel12.setText("City");

        cityCom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cityCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel15.setText("Subject");

        subCom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout mainLeftLayout = new javax.swing.GroupLayout(mainLeft);
        mainLeft.setLayout(mainLeftLayout);
        mainLeftLayout.setHorizontalGroup(
            mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLeftLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(69, 69, 69)
                        .addComponent(te_nic))
                    .addGroup(mainLeftLayout.createSequentialGroup()
                        .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(te_email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(te_line1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(te_line2)
                            .addComponent(te_lname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(te_fname)
                            .addGroup(mainLeftLayout.createSequentialGroup()
                                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainLeftLayout.createSequentialGroup()
                                        .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(te_no, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addComponent(genarate_btn))
                                    .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(te_mobile, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainLeftLayout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton2))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(mainLeftLayout.createSequentialGroup()
                        .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainLeftLayout.createSequentialGroup()
                                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subCom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityCom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        mainLeftLayout.setVerticalGroup(
            mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(te_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genarate_btn))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(te_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(te_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(te_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(te_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(te_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(te_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(te_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cityCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainRight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel14.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel14.setText("Type anythings related to teachers");

        anything_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anything_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anything_txtKeyReleased(evt);
            }
        });

        print_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        print_btn.setText("PRINT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Te_No", "Name", "NIC", "Gender", "Mobile", "Email", "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout mainRightLayout = new javax.swing.GroupLayout(mainRight);
        mainRight.setLayout(mainRightLayout);
        mainRightLayout.setHorizontalGroup(
            mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(mainRightLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainRightLayout.createSequentialGroup()
                        .addComponent(anything_txt)
                        .addGap(18, 18, 18)
                        .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainRightLayout.setVerticalGroup(
            mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anything_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(mainLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadCountry() {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `city`");

            Vector cityVector = new Vector();
            cityVector.add("Select City");

            while (rs.next()) {
                cityVector.add(rs.getString("name"));
                cityMap.put(rs.getString("name"), rs.getInt("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(cityVector);
            cityCom.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadSubjects() {

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `subjects`");

            Vector subjectVector = new Vector();
            subjectVector.add("Select Subject");

            while (rs.next()) {
                subjectVector.add(rs.getString("name"));
                subMap.put(rs.getString("name"), rs.getInt("Subno"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(subjectVector);
            subCom.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTeachers() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {

            ResultSet rs = MySQL.execute("SELECT * FROM `teachers` INNER JOIN `gender` ON `teachers`.`gender_id` = `gender`.`id` "
                    + "INNER JOIN `teacher_address` ON `teachers`.`Tno` = `teacher_address`.`teachers_Tno` INNER JOIN `subjects` ON `teachers`.`subjects_Subno` = `subjects`.`Subno` ORDER BY `reg_datetime` ASC");

            while (rs.next()) {

                Vector<String> vec = new Vector<>();
                vec.add(rs.getString("Tno"));
                vec.add(rs.getString("teFname") + " " + rs.getString("teLname"));
                vec.add(rs.getString("te_NIC"));
                vec.add(rs.getString("gender.gen"));
                vec.add(rs.getString("teMobile"));
                vec.add(rs.getString("teEmail"));
                vec.add(rs.getString("subjects.name"));

                model.addRow(vec);
                jTable1.setModel(model);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void genarate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarate_btnActionPerformed
        // TODO add your handling code here:

        Random random = new Random();
        int code = random.nextInt(9000) + 1000;
        int rowCount;

        try {
            ResultSet rs = MySQL.execute("SELECT COUNT(*) AS row_count FROM `teachers`");

            if (rs.next()) {

                rowCount = rs.getInt("row_count");
                int whichStudent = rowCount + 1;
                String newStuNumber = "TE_" + whichStudent + "_" + code;
                System.out.println(newStuNumber);

                te_no.setText(newStuNumber);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_genarate_btnActionPerformed

    private void clearinfor() {

        te_no.setText("");
        te_fname.setText("");
        te_lname.setText("");
        te_nic.setText("");
        te_mobile.setText("");
        te_email.setText("");
        te_line1.setText("");
        te_line2.setText("");
        cityCom.setSelectedIndex(0);
        edu_quali.setText("");
        prof_quali.setText("");
        subCom.setSelectedIndex(0);
        jRadioButton1.setSelected(true);

    }

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:

        int cityId;
        int subId;

        String Teacher_no = te_no.getText();
        String Fname = te_fname.getText();
        String Lname = te_lname.getText();
        String Nic = te_nic.getText();
        String Mobile = te_mobile.getText();
        String Email = te_email.getText();
        String Address1 = te_line1.getText();
        String Address2 = te_line2.getText();
        String city = String.valueOf(cityCom.getSelectedItem());
        String EduQ = edu_quali.getText();
        String ProfQ = prof_quali.getText();
        String Subject = String.valueOf(subCom.getSelectedItem());
        ButtonModel genderSelection = buttonGroup1.getSelection();

        Date date = jDateChooser1.getDate();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        if (Teacher_no.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Teacher Number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Fname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid First Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Lname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Nic.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid NIC", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (date == null) {
            JOptionPane.showMessageDialog(this, "Inavlid DOB", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (genderSelection == null) {
            JOptionPane.showMessageDialog(this, "Inavlid gender", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Mobile", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Email", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Address1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Addresss", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (EduQ.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inavlid Education Quali", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (city.equals("Select City")) {
            JOptionPane.showMessageDialog(this, "Inavlid City", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Subject.equals("Select Subject")) {
            JOptionPane.showMessageDialog(this, "Inavlid Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            String gender = buttonGroup1.getSelection().getActionCommand();

            cityId = cityMap.get(city);
            subId = subMap.get(Subject);

            String stDOB = format.format(date);
            System.out.println(stDOB);

            if (save_btn.getText().equals("SAVE")) {

                //Get Currrent date and time------------------------------------------
                Date currentDate = new Date();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String curentDate = format1.format(currentDate);

                try {

                    MySQL.execute("INSERT INTO `teachers` (`Tno`,`teFname`,`teLname`,`te_NIC`,`teDob`,`gender_id`,`teMobile`,`teEmail`,`teEduQualifi`,`teProfQualifi`,`subjects_Subno`,`reg_datetime`)"
                            + "VALUES ('" + Teacher_no + "','" + Fname + "','" + Lname + "','" + Nic + "','" + stDOB + "','" + gender + "','" + Mobile + "','" + Email + "','" + EduQ + "','" + ProfQ + "','" + subId + "',"
                                    + "'" + curentDate + "')");

                    MySQL.execute("INSERT INTO `teacher_address` (`line1`,`line2`,`city_id`,`teachers_Tno`)"
                            + "VALUES ('" + Address1 + "','" + Address2 + "','" + cityId + "','" + Teacher_no + "')");

                    JOptionPane.showMessageDialog(this, "Teacher Added Success", "System Message", JOptionPane.INFORMATION_MESSAGE);

                    loadTeachers();
                    clearinfor();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {

                try {

                    int selectedRow = jTable1.getSelectedRow();

                    String Tea_no = String.valueOf(jTable1.getValueAt(selectedRow, 0));

                    MySQL.execute("UPDATE `teachers` SET `teFname` = '" + Fname + "',`teLname` = '" + Lname + "',`te_NIC` = '" + Nic + "',`teDob` = '" + stDOB + "', `teMobile` = '" + Mobile + "',"
                            + "`teEmail` = '" + Email + "',`teEduQualifi` = '" + EduQ + "',`teProfQualifi` = '" + ProfQ + "',`subjects_Subno` = '" + subId + "',`gender_id` = '" + gender + "'"
                            + "WHERE `Tno` = '" + Tea_no + "'");

                    MySQL.execute("UPDATE `teacher_address` SET `line1` = '" + Address1 + "', `line2` = '" + Address2 + "', `city_id` = '" + cityId + "' WHERE `teachers_Tno` = '" + Tea_no + "'");

                    loadTeachers();
                    clearinfor();
                    save_btn.setText("SAVE");
                    clr_btn.setText("CLEAR");
                    genarate_btn.setEnabled(true);

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }

        }


    }//GEN-LAST:event_save_btnActionPerformed

    private void clr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_btnActionPerformed
        // TODO add your handling code here:
        if (clr_btn.getText().equals("CLEAR")) {
            clearinfor();
        } else {

            int selectedRow = jTable1.getSelectedRow();
            String tea_no = String.valueOf(jTable1.getValueAt(selectedRow, 0));

            try {

                MySQL.execute("DELETE FROM `teacher_address` WHERE `teachers_Tno` = '" + tea_no + "'");
                MySQL.execute("DELETE FROM `teachers` WHERE `Tno` = '" + tea_no + "'");

                JOptionPane.showMessageDialog(this, "Teacher Delete Successfull");

                loadTeachers();
                clearinfor();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_clr_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            genarate_btn.setEnabled(false);
            save_btn.setText("UPDATE");
            clr_btn.setText("DELETE");

            int slectedRow = jTable1.getSelectedRow();
            String Selected_TeuNo = String.valueOf(jTable1.getValueAt(slectedRow, 0));

            try {
                ResultSet rs = MySQL.execute("SELECT * FROM `teachers` INNER JOIN `gender` ON `teachers`.`gender_id` = `gender`.`id` "
                        + "INNER JOIN `teacher_address` ON `teachers`.`Tno` = `teacher_address`.`teachers_Tno` INNER JOIN `subjects` ON `teachers`.`subjects_Subno` = `subjects`.`Subno` WHERE `Tno` = '" + Selected_TeuNo + "'");

                if (rs.next()) {

                    te_no.setText(rs.getString("Tno"));
                    te_fname.setText(rs.getString("teFname"));
                    te_lname.setText(rs.getString("teLname"));
                    te_nic.setText(rs.getString("te_NIC"));

                    Date dobDate = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    dobDate = dateFormat.parse(rs.getString("teDob"));
                    jDateChooser1.setDate(dobDate);

                    if ("Male".equals(rs.getString("gender.gen"))) {
                        jRadioButton1.setSelected(true);
                    } else {
                        jRadioButton2.setSelected(true);
                    }

                    te_mobile.setText(rs.getString("teMobile"));
                    te_email.setText(rs.getString("teEmail"));
                    te_line1.setText(rs.getString("teacher_address.line1"));
                    te_line2.setText(rs.getString("teacher_address.line2"));
                    cityCom.setSelectedIndex(rs.getInt("teacher_address.city_id"));
                    edu_quali.setText(rs.getString("teEduQualifi"));
                    prof_quali.setText(rs.getString("teProfQualifi"));
                    subCom.setSelectedIndex(rs.getInt("subjects_Subno"));

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void anything_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anything_txtKeyReleased
        // TODO add your handling code here:
        
            
        if (anything_txt.getText().equals("")) {
            loadTeachers();
        } else {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            try {
                ResultSet rs = MySQL.execute("SELECT * FROM `teachers` INNER JOIN `gender` ON `teachers`.`gender_id` = `gender`.`id` INNER JOIN `subjects` ON `teachers`.`subjects_Subno` = `subjects`.`Subno`"
                        + " WHERE `teFname` LIKE '" + anything_txt.getText() + "%' OR `teLname` LIKE '" + anything_txt.getText() + "%' OR"
                        + "`te_NIC` LIKE '" + anything_txt.getText() + "%' OR `gen` LIKE '" + anything_txt.getText() + "%'"
                        + "OR `teDob` LIKE '" + anything_txt.getText() + "%' OR `teMobile` LIKE '" + anything_txt.getText() + "%' OR `name` LIKE '"+anything_txt.getText()+"%'");

                while (rs.next()) {

                    Vector<String> vec = new Vector<>();
                    vec.add(rs.getString("Tno"));
                    vec.add(rs.getString("teFname") + " " + rs.getString("teLname"));
                    vec.add(rs.getString("te_NIC"));
                    vec.add(rs.getString("gender.gen"));
                    vec.add(rs.getString("teMobile"));
                    vec.add(rs.getString("teEmail"));
                    vec.add(rs.getString("subjects.name"));

                    model.addRow(vec);
                    jTable1.setModel(model);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_anything_txtKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//        /* Set the Theam look and feel */
//        IntelliJTheme.setup(Student_Registration.class.getResourceAsStream(
//                "/themes/one_dark.theme.json"));
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Teacher_Enrolment().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImgBtn;
    private javax.swing.JTextField anything_txt;
    private javax.swing.JPanel btnPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cityCom;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clr_btn;
    private javax.swing.JTextArea edu_quali;
    private javax.swing.JButton genarate_btn;
    private javax.swing.JLabel imgFrame;
    private javax.swing.JPanel imgFramePanel;
    private com.toedter.calendar.JCalendar jCalendar2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainLeft;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainRight;
    private javax.swing.JButton print_btn;
    private javax.swing.JTextArea prof_quali;
    private javax.swing.JButton save_btn;
    private javax.swing.JComboBox<String> subCom;
    private javax.swing.JTextField te_email;
    private javax.swing.JTextField te_fname;
    private javax.swing.JTextField te_line1;
    private javax.swing.JTextField te_line2;
    private javax.swing.JTextField te_lname;
    private javax.swing.JTextField te_mobile;
    private javax.swing.JTextField te_nic;
    private javax.swing.JTextField te_no;
    private javax.swing.JLabel userImg;
    // End of variables declaration//GEN-END:variables
}
